services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/certs:/etc/ssl/certs:ro
      - ./volumes/nginx/conf:/etc/nginx/conf.d:ro
    restart: unless-stopped
    networks:
      - web
      - intern
      - media

  # ddclient:
  #   image: lscr.io/linuxserver/ddclient:latest
  #   container_name: ddclient
  #   environment:
  #     - PUID=501
  #     - PGID=20
  #     - TZ=Europe/Zurich
  #   volumes:
  #     - ./volumes/ddclient:/config
  #   restart: unless-stopped

  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - INIT_ASSETS=0
      - PUID=501
      - PGID=20
    volumes:
      - ./volumes/homer:/www/assets
    ports:
      - 8080:8080
    networks:
      - media
      - web

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/radarr:/config
      - ./data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/sonarr:/config
      - ./data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/lidarr:/config
      - ./data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - media

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/sabnzbd:/config
      - ./data/usenet:/downloads
    ports:
      - "9000:8080"
    restart: unless-stopped
    networks:
      - media

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    networks:
      - media

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=501
      - PGID=20
      - UMASK=002
      - TZ=Europe/Zurich
    volumes:
      - ./volumes/jellyfin:/config
      - ./data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - media

networks:
  web:
    driver: bridge
  intern:
  monitoring:
  media:
